### ISSUE TITLE
Unmapped data is not available in FormEvent

### ISSUE THREAD

**Issue by elements-team** [passioneight/form-builder#1]
**Describe the bug**
When using entities with a from, any unmapped data is not available in the `FormEvent`. Thus, one will have to inject the `RequestStack` and access any these values via the `Request` directly.

**To Reproduce**
1. Create a form which uses an entity.
2. Have some fields be defined as `mapped => false`.
3. Create an event listener for the form and try to access the unmapped fields.

**Expected behavior**
Any unmapped data is available without the necessity of injecting the `RequestStack`.

**Proposed solution**
The `FormEvent`'s `getData` method should actually hold the request data. For the entity to be accessed, another method should be introduced (e.g., `getEntity`).

**Additional context**
Note that this would be a breaking change for all event listeners which rely on `getData` returning the entity.

**Comment by passioneight** [comment]
You can access unmapped data via your form.

Use the following code in your listener:

```php
$form = $formEvent->getForm();
$value = $form->get('myfield')->getData();
```

I think we should update the documentation, so that it becomes clear how to handle this use case.
